name: tests

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PORT: "3000"
      JWT_SIGN_KEY: "sample"
      JWT_EXPIRATION_TIME_SEC: "300"
    
    steps:
      - uses: actions/checkout@v2
      - run: npm install && npm run test:ci
