name: tests

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm install and run jest test
        env:
          PORT: "3000"
          JWT_SIGN_KEY: "sample"
          JWT_EXPIRATION_TIME_SEC: "300"
        run: |
          npm install
          npm run test:ci
